### ISSUE TITLE
Review pull requests from the original repo.

### ISSUE THREAD

**Issue by DaloLorn** [OpenSRProject/OpenStarRuler#4]
These pull requests need to be reviewed and possibly merged into the repo:

- [x] BlindMindStudios/StarRuler2-Source#55
- [ ] BlindMindStudios/StarRuler2-Source#56
- [ ] BlindMindStudios/StarRuler2-Source#58
- [ ] BlindMindStudios/StarRuler2-Source#70
- [x] BlindMindStudios/StarRuler2-Source#78 (IIRC, KB already committed this to OSR-Source)

**Comment by kb-1000** [comment]
I've actually done BlindMindStudios#55 already in 50a99418fd1cf7642e23ed3ac48dcac1faefdc0f. BlindMindStudios#70 has a commit with the same content.

**Comment by DaloLorn** [comment]
> [BlindMindStudios#70](https://github.com/BlindMindStudios/StarRuler2-Source/pull/70) has a commit with the same content.

It does, yes, but it also contains other things besides that.
